// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Picasso.Data;

namespace Picasso.Migrations
{
    [DbContext(typeof(DataBase))]
    [Migration("20211011120407_N1")]
    partial class N1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Picasso.Models.DataBase.SearchUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("A")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("A");

                    b.Property<string>("CNAME")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CNAME");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<DateTime>("DateAdd")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_date");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("update_date");

                    b.Property<string>("Domain")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.Property<string>("IsDead")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("isDead");

                    b.Property<string>("MX")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MX");

                    b.Property<string>("NS")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NS");

                    b.Property<string>("TXT")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TXT");

                    b.Property<string>("Url")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.Property<string>("UrlToUpper")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url_to_upper");

                    b.HasKey("Id");

                    b.ToTable("SearchUrl");
                });
#pragma warning restore 612, 618
        }
    }
}
